spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SKED
    username: postgres
    password: Azimbaev2004
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  header: Authorization
  prefix: Bearer
  login: /login
  refresh: /refresh
  register: /register
  logout: /logout
  user: /user
  password: /password
  email: /email
  username: /username
  role: /role
  id: /id
  all: /all
  delete: /delete
  update: /update
  